import { DatabaseSync } from "node:sqlite";
import path from "node:path";
import { upsertPerson, upsertList, addToList } from "../lib/resources/audience";
import { createDraft, publishContent } from "../lib/resources/content";

const dbFile = path.resolve("data/pulse.db");
console.log("Using database:", dbFile);

const db = new DatabaseSync(dbFile);
const biz = db.prepare("SELECT id FROM businesses ORDER BY created_at ASC LIMIT 1").get();
db.close();

if (!biz) {
  console.error("No business found in DB!");
  process.exit(1);
}

const businessId = biz.id;
console.log("Found Business ID:", businessId);

// 1. Add Arjun Ramachandran to audience
const person = upsertPerson(businessId, {
  email: "arjun.ramachandran96@gmail.com",
  name: "Arjun Ramachandran",
  traits: { role: "VIP Client", source: "Direct Test" },
});
console.log("Upserted Person:", JSON.stringify(person, null, 2));

// 2. Create VIP Client List and add person
const list = upsertList(businessId, {
  name: "VIP Clients",
  description: "Targeted list for VIP client communications",
});
console.log("Upserted List:", JSON.stringify(list, null, 2));

const addedRes = addToList(businessId, list.slug, ["arjun.ramachandran96@gmail.com"]);
console.log("Added to List result:", JSON.stringify(addedRes, null, 2));

// 3. Draft test email content
const draft = createDraft(businessId, {
  kind: "email",
  title: "Welcome & Pulse Platform Direct Demonstration",
  body: `# Hello Arjun,

This is a live test email generated by **Pulse — Autonomous Marketing Platform**.

### Campaign Details:
- **Recipient:** Arjun Ramachandran (arjun.ramachandran96@gmail.com)
- **Status:** Published & Dispatched
- **Agent:** Pulse AI Opus 5
- **Mode:** Production / Demo Verification

Thank you for testing Pulse!
`,
  listSlug: list.slug,
  createdBy: "agent",
  meta: {
    subject: "⚡ Test Email: Pulse AI Agent Direct Outreach to Arjun",
    preheader: "Live test demonstration of email campaign dispatch",
    tags: ["test-campaign", "vip"],
  },
});

console.log("Draft Created:", JSON.stringify(draft, null, 2));

// 4. Publish email (simulating agent/human approved sending)
const published = publishContent(businessId, draft.id);
console.log("Email Successfully Published & Dispatched! Result:", JSON.stringify(published, null, 2));
